### ISSUE TITLE
button to delete xpost snippets

### ISSUE THREAD

**Issue by extremepayne** [PrismLauncher/bot#116]
refraction will helpfully post in a message when you paste a discord link. sometimes you don’t want that. there should be a button that only the link paster can press to delete the embedded message.

**Comment by IThundxr** [comment]
I can add this but is there really a good reason to?

**Comment by IThundxr** [comment]
even then ill make a pr up to ryan to decide if they wanna accept

**Comment by IThundxr** [comment]
https://github.com/PrismLauncher/bot/pull/117

**Comment by IThundxr** [comment]
Completed in https://github.com/PrismLauncher/bot/pull/117

**Comment by extremepayne** [comment]
can confirm
